from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calculator(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(281, 458)
        MainWindow.setIconSize(QtCore.QSize(30, 30))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(0, 0, 281, 111))
        self.lcdNumber.setObjectName("lcdNumber")
        self.C = QtWidgets.QPushButton(self.centralwidget)
        self.C.setGeometry(QtCore.QRect(0, 110, 71, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.C.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.C.setFont(font)
        self.C.setText("C")
        self.C.setIconSize(QtCore.QSize(20, 20))
        self.C.setObjectName("C")
        self.C_2 = QtWidgets.QPushButton(self.centralwidget)
        self.C_2.setGeometry(QtCore.QRect(70, 110, 71, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.C_2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.C_2.setFont(font)
        self.C_2.setText("←")
        self.C_2.setIconSize(QtCore.QSize(20, 20))
        self.C_2.setObjectName("C_2")
        self.C_3 = QtWidgets.QPushButton(self.centralwidget)
        self.C_3.setGeometry(QtCore.QRect(210, 110, 71, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.C_3.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.C_3.setFont(font)
        self.C_3.setText("÷")
        self.C_3.setIconSize(QtCore.QSize(20, 20))
        self.C_3.setObjectName("C_3")
        self.C_4 = QtWidgets.QPushButton(self.centralwidget)
        self.C_4.setGeometry(QtCore.QRect(140, 110, 71, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.C_4.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.C_4.setFont(font)
        self.C_4.setText("%")
        self.C_4.setIconSize(QtCore.QSize(20, 20))
        self.C_4.setObjectName("C_4")
        self.C_5 = QtWidgets.QPushButton(self.centralwidget)
        self.C_5.setGeometry(QtCore.QRect(140, 180, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.C_5.setFont(font)
        self.C_5.setText("9")
        self.C_5.setIconSize(QtCore.QSize(20, 20))
        self.C_5.setObjectName("C_5")
        self.C_6 = QtWidgets.QPushButton(self.centralwidget)
        self.C_6.setGeometry(QtCore.QRect(70, 180, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.C_6.setFont(font)
        self.C_6.setText("8")
        self.C_6.setIconSize(QtCore.QSize(20, 20))
        self.C_6.setObjectName("C_6")
        self.C_7 = QtWidgets.QPushButton(self.centralwidget)
        self.C_7.setGeometry(QtCore.QRect(0, 180, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.C_7.setFont(font)
        self.C_7.setText("7")
        self.C_7.setIconSize(QtCore.QSize(20, 20))
        self.C_7.setObjectName("C_7")
        self.C_8 = QtWidgets.QPushButton(self.centralwidget)
        self.C_8.setGeometry(QtCore.QRect(210, 180, 71, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.C_8.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.C_8.setFont(font)
        self.C_8.setText("×")
        self.C_8.setIconSize(QtCore.QSize(20, 20))
        self.C_8.setObjectName("C_8")
        self.C_9 = QtWidgets.QPushButton(self.centralwidget)
        self.C_9.setGeometry(QtCore.QRect(140, 250, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.C_9.setFont(font)
        self.C_9.setText("6")
        self.C_9.setIconSize(QtCore.QSize(20, 20))
        self.C_9.setObjectName("C_9")
        self.C_10 = QtWidgets.QPushButton(self.centralwidget)
        self.C_10.setGeometry(QtCore.QRect(140, 320, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.C_10.setFont(font)
        self.C_10.setText("3")
        self.C_10.setIconSize(QtCore.QSize(20, 20))
        self.C_10.setObjectName("C_10")
        self.C_11 = QtWidgets.QPushButton(self.centralwidget)
        self.C_11.setGeometry(QtCore.QRect(70, 250, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.C_11.setFont(font)
        self.C_11.setText("5")
        self.C_11.setIconSize(QtCore.QSize(20, 20))
        self.C_11.setObjectName("C_11")
        self.C_12 = QtWidgets.QPushButton(self.centralwidget)
        self.C_12.setGeometry(QtCore.QRect(0, 250, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.C_12.setFont(font)
        self.C_12.setText("4")
        self.C_12.setIconSize(QtCore.QSize(20, 20))
        self.C_12.setObjectName("C_12")
        self.C_13 = QtWidgets.QPushButton(self.centralwidget)
        self.C_13.setGeometry(QtCore.QRect(210, 320, 71, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.C_13.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.C_13.setFont(font)
        self.C_13.setText("+")
        self.C_13.setIconSize(QtCore.QSize(20, 20))
        self.C_13.setObjectName("C_13")
        self.C_14 = QtWidgets.QPushButton(self.centralwidget)
        self.C_14.setGeometry(QtCore.QRect(0, 320, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.C_14.setFont(font)
        self.C_14.setText("1")
        self.C_14.setIconSize(QtCore.QSize(20, 20))
        self.C_14.setObjectName("C_14")
        self.C_15 = QtWidgets.QPushButton(self.centralwidget)
        self.C_15.setGeometry(QtCore.QRect(70, 320, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.C_15.setFont(font)
        self.C_15.setText("2")
        self.C_15.setIconSize(QtCore.QSize(20, 20))
        self.C_15.setObjectName("C_15")
        self.C_16 = QtWidgets.QPushButton(self.centralwidget)
        self.C_16.setGeometry(QtCore.QRect(210, 250, 71, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.C_16.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.C_16.setFont(font)
        self.C_16.setText("-")
        self.C_16.setIconSize(QtCore.QSize(20, 20))
        self.C_16.setObjectName("C_16")
        self.C_17 = QtWidgets.QPushButton(self.centralwidget)
        self.C_17.setGeometry(QtCore.QRect(70, 390, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.C_17.setFont(font)
        self.C_17.setText(",")
        self.C_17.setIconSize(QtCore.QSize(20, 20))
        self.C_17.setObjectName("C_17")
        self.C_19 = QtWidgets.QPushButton(self.centralwidget)
        self.C_19.setGeometry(QtCore.QRect(140, 390, 141, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.C_19.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.C_19.setFont(font)
        self.C_19.setText("=")
        self.C_19.setIconSize(QtCore.QSize(20, 20))
        self.C_19.setObjectName("C_19")
        self.C_20 = QtWidgets.QPushButton(self.centralwidget)
        self.C_20.setGeometry(QtCore.QRect(0, 390, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.C_20.setFont(font)
        self.C_20.setText("0")
        self.C_20.setIconSize(QtCore.QSize(20, 20))
        self.C_20.setObjectName("C_20")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
