from PyQt5 import QtCore, QtGui, QtWidgets
from calculator_logic import push_number as pn


class Calculator(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()

        self.setupUi(self)
        self.li = []
        self.cleared = True

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Calculator")
        MainWindow.setEnabled(True)
        MainWindow.resize(281, 402)
        MainWindow.setIconSize(QtCore.QSize(30, 30))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.C = QtWidgets.QPushButton(self.centralwidget)
        self.C.setGeometry(QtCore.QRect(0, 50, 71, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.C.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.C.setFont(font)
        self.C.setText("C")
        self.C.setIconSize(QtCore.QSize(20, 20))
        self.C.setObjectName("C")
        self.Backspace = QtWidgets.QPushButton(self.centralwidget)
        self.Backspace.setGeometry(QtCore.QRect(70, 50, 71, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Backspace.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Backspace.setFont(font)
        self.Backspace.setText("←")
        self.Backspace.setIconSize(QtCore.QSize(20, 20))
        self.Backspace.setObjectName("Backspace")
        self.Division = QtWidgets.QPushButton(self.centralwidget)
        self.Division.setGeometry(QtCore.QRect(210, 50, 71, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Division.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Division.setFont(font)
        self.Division.setText("÷")
        self.Division.setIconSize(QtCore.QSize(20, 20))
        self.Division.setObjectName("Division")
        self.Percent = QtWidgets.QPushButton(self.centralwidget)
        self.Percent.setGeometry(QtCore.QRect(140, 50, 71, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Percent.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Percent.setFont(font)
        self.Percent.setText("%")
        self.Percent.setIconSize(QtCore.QSize(20, 20))
        self.Percent.setObjectName("Percent")
        self.Nine = QtWidgets.QPushButton(self.centralwidget)
        self.Nine.setGeometry(QtCore.QRect(140, 120, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Nine.setFont(font)
        self.Nine.setText("9")
        self.Nine.setIconSize(QtCore.QSize(20, 20))
        self.Nine.setObjectName("Nine")
        self.Eight = QtWidgets.QPushButton(self.centralwidget)
        self.Eight.setGeometry(QtCore.QRect(70, 120, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Eight.setFont(font)
        self.Eight.setText("8")
        self.Eight.setIconSize(QtCore.QSize(20, 20))
        self.Eight.setObjectName("Eight")
        self.Seven = QtWidgets.QPushButton(self.centralwidget)
        self.Seven.setGeometry(QtCore.QRect(0, 120, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Seven.setFont(font)
        self.Seven.setText("7")
        self.Seven.setIconSize(QtCore.QSize(20, 20))
        self.Seven.setObjectName("Seven")
        self.Multiple = QtWidgets.QPushButton(self.centralwidget)
        self.Multiple.setGeometry(QtCore.QRect(210, 120, 71, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Multiple.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Multiple.setFont(font)
        self.Multiple.setText("×")
        self.Multiple.setIconSize(QtCore.QSize(20, 20))
        self.Multiple.setObjectName("Multiple")
        self.Six = QtWidgets.QPushButton(self.centralwidget)
        self.Six.setGeometry(QtCore.QRect(140, 190, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Six.setFont(font)
        self.Six.setText("6")
        self.Six.setIconSize(QtCore.QSize(20, 20))
        self.Six.setObjectName("Six")
        self.Three = QtWidgets.QPushButton(self.centralwidget)
        self.Three.setGeometry(QtCore.QRect(140, 260, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Three.setFont(font)
        self.Three.setText("3")
        self.Three.setIconSize(QtCore.QSize(20, 20))
        self.Three.setObjectName("Three")
        self.Five = QtWidgets.QPushButton(self.centralwidget)
        self.Five.setGeometry(QtCore.QRect(70, 190, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Five.setFont(font)
        self.Five.setText("5")
        self.Five.setIconSize(QtCore.QSize(20, 20))
        self.Five.setObjectName("Five")
        self.Four = QtWidgets.QPushButton(self.centralwidget)
        self.Four.setGeometry(QtCore.QRect(0, 190, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Four.setFont(font)
        self.Four.setText("4")
        self.Four.setIconSize(QtCore.QSize(20, 20))
        self.Four.setObjectName("Four")
        self.Addition = QtWidgets.QPushButton(self.centralwidget)
        self.Addition.setGeometry(QtCore.QRect(210, 260, 71, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Addition.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Addition.setFont(font)
        self.Addition.setText("+")
        self.Addition.setIconSize(QtCore.QSize(20, 20))
        self.Addition.setObjectName("Addition")
        self.One = QtWidgets.QPushButton(self.centralwidget)
        self.One.setGeometry(QtCore.QRect(0, 260, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.One.setFont(font)
        self.One.setText("1")
        self.One.setIconSize(QtCore.QSize(20, 20))
        self.One.setObjectName("One")
        self.Two = QtWidgets.QPushButton(self.centralwidget)
        self.Two.setGeometry(QtCore.QRect(70, 260, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Two.setFont(font)
        self.Two.setText("2")
        self.Two.setIconSize(QtCore.QSize(20, 20))
        self.Two.setObjectName("Two")
        self.Subtraction = QtWidgets.QPushButton(self.centralwidget)
        self.Subtraction.setGeometry(QtCore.QRect(210, 190, 71, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Subtraction.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Subtraction.setFont(font)
        self.Subtraction.setText("-")
        self.Subtraction.setIconSize(QtCore.QSize(20, 20))
        self.Subtraction.setObjectName("Subtraction")
        self.Dot = QtWidgets.QPushButton(self.centralwidget)
        self.Dot.setGeometry(QtCore.QRect(70, 330, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Dot.setFont(font)
        self.Dot.setText(".")
        self.Dot.setIconSize(QtCore.QSize(20, 20))
        self.Dot.setObjectName("Dot")
        self.Equally = QtWidgets.QPushButton(self.centralwidget)
        self.Equally.setGeometry(QtCore.QRect(140, 330, 141, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.Equally.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Equally.setFont(font)
        self.Equally.setText("=")
        self.Equally.setIconSize(QtCore.QSize(20, 20))
        self.Equally.setObjectName("Equally")
        self.Zero = QtWidgets.QPushButton(self.centralwidget)
        self.Zero.setGeometry(QtCore.QRect(0, 330, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Zero.setFont(font)
        self.Zero.setText("0")
        self.Zero.setIconSize(QtCore.QSize(20, 20))
        self.Zero.setObjectName("Zero")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setGeometry(QtCore.QRect(0, 0, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.Addition.clicked.connect(lambda: pn(self, self.Addition))
        self.Zero.clicked.connect(lambda: pn(self, self.Zero))
        self.Backspace.clicked.connect(lambda: pn(self, self.Backspace))
        self.C.clicked.connect(lambda: pn(self, self.C))
        self.Division.clicked.connect(lambda: pn(self, self.Division))
        self.Dot.clicked.connect(lambda: pn(self, self.Dot))
        self.Eight.clicked.connect(lambda: pn(self, self.Eight))
        self.Equally.clicked.connect(lambda: pn(self, self.Equally))
        self.Five.clicked.connect(lambda: pn(self, self.Five))
        self.Four.clicked.connect(lambda: pn(self, self.Four))
        self.Multiple.clicked.connect(lambda: pn(self, self.Multiple))
        self.Nine.clicked.connect(lambda: pn(self, self.Nine))
        self.One.clicked.connect(lambda: pn(self, self.One))
        self.Percent.clicked.connect(lambda: pn(self, self.Percent))
        self.Seven.clicked.connect(lambda: pn(self, self.Seven))
        self.Six.clicked.connect(lambda: pn(self, self.Six))
        self.Subtraction.clicked.connect(lambda: pn(self, self.Subtraction))
        self.Three.clicked.connect(lambda: pn(self, self.Three))
        self.Two.clicked.connect(lambda: pn(self, self.Two))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
